{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: k8s-dns-node-cache
      toPorts:
        - ports:
            - port: "1053"
              protocol: UDP
            - port: "1053"
              protocol: TCP
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress:
    # Allow Valkey client connections
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "6379"
          protocol: TCP
    # Allow Prometheus metrics scraping
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "9121"
          protocol: TCP
{{ end }}

