# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2

# Version of the packaged app
appVersion: 8.1.4

# Make sure your name DOES NOT end in "app" or "-app".
name: valkey

# Please describe what the app provides in a sentence or two.
description: A Giant Swarm app for deploying Valkey (a Redis alternative) on Kubernetes.

# URL of the GitHub repository that is the source of this Chart.yaml file.
home: https://github.com/giantswarm/valkey-app

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
#icon: https://s.giantswarm.io/app-icons/valkey/1/light.svg

sources:
  - https://github.com/valkey-io/valkey-helm
version: 0.0.0-dev
annotations:
  application.giantswarm.io/team: planeteers
  # Adapt to 'giantswarm' if this application is not to be deployed by customers
  io.giantswarm.application.audience: all
  # Adapt to 'true' if Giant Swarm takes responsibility for this app where it's deployed
  io.giantswarm.application.managed: "false"
  config.giantswarm.io/version: 1.x.x
dependencies:
  - name: valkey
    repository: file://charts/valkey
    version: 0.8.1
